version: '3.8'

services:
  payment-gateway:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
