name: Continuous Deployment

on:
  push:
    branches:
      - main # Change to your default branch if not 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    environment: development

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push to DockerHub
        run: |
          docker-compose -f docker-compose.yml build
          # Tag the image with the desired repository and tag name
          docker tag your-image-name:latest ridwanrais/golang-payment-gateway:latest
          docker push ridwanrais/golang-payment-gateway:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    environment: development

    steps:
      - name: SSH and Deploy on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            cd /path/on/ec2/
            
            # Pull the specific image from the repository
            docker pull ridwanrais/golang-payment-gateway:latest

            # Stop the running services (if any)
            docker-compose -f docker-compose.yml down

            # Start the services with the new image
            docker-compose -f docker-compose.yml up -d
